//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/29/2019 9:55:51 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VinarishLib.Models
{
    public partial class Reporter
    {
        public Reporter()
        {
            this.Reports = new List<Report>();
            this.Trips = new List<TrainTrip>();
            this.AsAssistant = new List<Assistant>();
            OnCreated();
        }

        public virtual int ReporterId
        {
            get;
            set;
        }

        public virtual string VinarishUserId
        {
            get;
            set;
        }

        [DisplayName(Expressions.Departments)]
        public virtual Guid DepartmentId
        {
            get;
            set;
        }

        [DisplayName(Expressions.UserName)]
        public virtual string UserName
        {
            get;
            set;
        }

        [DisplayName(Expressions.Reports)]
        public virtual IList<Report> Reports
        {
            get;
            set;
        }

        [DisplayName(Expressions.Departments)]
        public virtual Department Department
        {
            get;
            set;
        }

        [DisplayName(Expressions.Trips)]
        public virtual IList<TrainTrip> Trips
        {
            get;
            set;
        }

        [DisplayName(Expressions.AsAssistant)]
        public virtual IList<Assistant> AsAssistant
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion Extensibility Method Definitions
    }
}