//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/29/2019 9:55:51 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace VinarishLib.Models
{
    public partial class TrainTrip
    {
        public TrainTrip()
        {
            WagonsOfTrip = new List<WagonTrip>();
            OnCreated();
        }

        public virtual Guid TrainTripId
        {
            get;
            set;
        }

        [DisplayName(Expressions.DateTime)]
        public virtual DateTime DateTime
        {
            get;
            set;
        }

        [DisplayName(Expressions.Train)]
        public virtual int TrainId
        {
            get;
            set;
        }

        [DisplayName(Expressions.Train)]
        public virtual Train Train
        {
            get;
            set;
        }

        [DisplayName(Expressions.Wagons)]
        public virtual IList<WagonTrip> WagonsOfTrip
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion Extensibility Method Definitions
    }
}