//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/29/2019 9:55:51 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VinarishLib.Models
{
    public enum DeviceStatusType : int
    {
        [Display(Name = Expressions.DeviceStatusMalfunction)]
        Malfunction,

        [Display(Name = Expressions.DeviceStatusRepair)]
        Repair,

        [Display(Name = Expressions.DeviceStatusNRepair)]
        Unrepairable
    }
}