//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/29/2019 9:55:51 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VinarishApi.Models
{
    public partial class WagonTrip
    {
        public WagonTrip()
        {
            this.Reports = new List<Report>();
            OnCreated();
        }

        public virtual System.Guid WagonTripId
        {
            get;
            set;
        }

        public virtual System.Guid WagonId
        {
            get;
            set;
        }

        public virtual System.Guid TrainTripId
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.Wagon)]
        public virtual Wagon Wagon
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.Trips)]
        public virtual TrainTrip TrainTrip
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.Reports)]
        public virtual IList<Report> Reports
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion Extensibility Method Definitions
    }
}