//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/21/2019 8:33:45 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VinarishMvc.Models
{
    public partial class DeviceType {

        public DeviceType()
        {
            this.DevicePlaces = new List<DevicePlace>();
            OnCreated();
        }

        public virtual int DeviceTypeId
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual int DepartmentId
        {
            get;
            set;
        }

        public virtual Department Department
        {
            get;
            set;
        }

        public virtual IList<DevicePlace> DevicePlaces
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
