//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/21/2019 8:33:45 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VinarishMvc.Models
{
    public partial class TrainTrip {

        public TrainTrip()
        {
            this.WagonsOfTrip = new List<WagonTrip>();
            OnCreated();
        }

        public virtual int TrainTripId
        {
            get;
            set;
        }

        public virtual System.DateTime DateTime
        {
            get;
            set;
        }

        public virtual int TrainId
        {
            get;
            set;
        }

        public virtual int ReporterId
        {
            get;
            set;
        }

        public virtual Train Train
        {
            get;
            set;
        }

        public virtual IList<WagonTrip> WagonsOfTrip
        {
            get;
            set;
        }

        public virtual Reporter Reporter
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
