//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/21/2019 12:55:20 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VinarishMvc.Models
{
    public partial class WagonTrip {

        public WagonTrip()
        {
            OnCreated();
        }

        public virtual int WagonTripId
        {
            get;
            set;
        }

        public virtual int WagonId
        {
            get;
            set;
        }

        public virtual int TrainTripId
        {
            get;
            set;
        }

        public virtual Wagon Wagon
        {
            get;
            set;
        }

        public virtual TrainTrip TrainTrip
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
