//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/29/2019 9:55:51 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VinarishMvc.Models
{
    public partial class Report
    {

        public Report()
        {
            this.AppendixReports = new List<Report>();
            OnCreated();
        }

        public virtual int ReportId
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.DateTime)]
        public virtual System.DateTime DateTimeCreated
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.DateTimeModified)]
        public virtual System.DateTime DateTimeModified
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.Reporter)]
        public virtual int ReporterId
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.Status)]
        public virtual ReportStatus Status
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.DeviceStatus)]
        public virtual System.Guid DeviceStatusId
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.ParentReport)]
        public virtual int? ParentReportId
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.DevicePlaces)]
        public virtual System.Guid DevicePlaceId
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.Wagon)]
        public virtual System.Guid WagonId
        {
            get;
            set;
        }

        public virtual System.Guid? WagonTripId
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.Code+Expressions.Report)]
        public virtual string Code
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.Reporter)]
        public virtual Reporter Reporter
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.DeviceStatus)]
        public virtual DeviceStatus DeviceStatus
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.ChildReports)]
        public virtual IList<Report> AppendixReports
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.ParentReport)]
        public virtual Report ParentReport
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.DevicePlaces)]
        public virtual DevicePlace DevicePlace
        {
            get;
            set;
        }

        [System.ComponentModel.DisplayName(Expressions.Wagon)]
        public virtual Wagon Wagon
        {
            get;
            set;
        }

        public virtual WagonTrip WagonTrip
        {
            get;
            set;
        }

        [DisplayName(Expressions.Site)]
        public virtual int? SiteId { get; set; }

        [DisplayName(Expressions.Site)]
        public virtual Site Site { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
